### ISSUE TITLE
[FEAT] Support multiple actions from one desktop entry.

### ISSUE THREAD

**Issue by Eric-Song-Nop** [fzdwx/launcher#1]
From [Specific of Desktop Entry](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-1.1.html), there can be multiple actions from one desktop entry, a common case is normal and private window for browser, I how this can be implemented for drun, **and I would be happy to implement it**.

**Comment by fzdwx** [comment]
Cool !
